# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-08 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='iso 4217 currency code', max_length=3, unique=True, verbose_name='code')),
                ('name', models.CharField(help_text='plain text name of the currency', max_length=64, verbose_name='name')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='HotelOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.PositiveIntegerField(help_text='the hotel providing the offer', verbose_name='hotel id')),
                ('days', models.PositiveSmallIntegerField(help_text='number of days in the offer', verbose_name='days')),
            ],
            options={
                'verbose_name': 'hotel offer',
                'verbose_name_plural': 'hotel offers',
            },
        ),
        migrations.CreateModel(
            name='Hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='the day for links', verbose_name='day')),
                ('hour', models.PositiveSmallIntegerField(help_text='the hour of the day', verbose_name='hour')),
            ],
            options={
                'verbose_name': 'hour',
                'verbose_name_plural': 'hours',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.PositiveIntegerField(help_text='the hotel providing the offer', verbose_name='hotel id')),
                ('price_usd', models.DecimalField(decimal_places=10, help_text='price converted to american dollars', max_digits=20, verbose_name='prince in usd')),
                ('original_price', models.DecimalField(decimal_places=10, help_text='original price of the offer', max_digits=20, verbose_name='original price')),
                ('breakfast_included', models.BooleanField(help_text='whether breakfast is included in the price', verbose_name='breakfast included')),
                ('valid_from_date', models.DateField(help_text='date from which this offer is valid', verbose_name='valid from date')),
                ('valid_to_date', models.DateField(help_text='date when this offer becomes invalid', verbose_name='valid to date')),
                ('valid_from_time', models.TimeField(help_text='time of the day this offer becomes valid', verbose_name='valid from time')),
                ('valid_to_time', models.TimeField(help_text='time of day this offer becomes invalid', verbose_name='valid to time')),
                ('checkin_date', models.DateField(help_text='date the guest must check-in', verbose_name='check-in date')),
                ('checkout_date', models.DateField(help_text='date the guest must check-out', verbose_name='check-out date')),
                ('original_currency', models.ForeignKey(help_text='currency of the original price', on_delete=django.db.models.deletion.CASCADE, related_name='offer_set', to='hq_hotel_mart.Currency', verbose_name='original currency')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
            },
        ),
        migrations.AlterUniqueTogether(
            name='hour',
            unique_together=set([('day', 'hour')]),
        ),
        migrations.AddField(
            model_name='hoteloffer',
            name='hour',
            field=models.ForeignKey(help_text='hour on which this offer is valid', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_offers', to='hq_hotel_mart.Hour', verbose_name='hour'),
        ),
        migrations.AddField(
            model_name='hoteloffer',
            name='offer_id',
            field=models.ForeignKey(help_text='the offer that is valid at this point in time', on_delete=django.db.models.deletion.CASCADE, related_name='offer_hours', to='hq_hotel_mart.Offer', verbose_name='offer'),
        ),
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together=set([('hotel_id', 'breakfast_included', 'checkin_date', 'checkout_date')]),
        ),
        migrations.AlterIndexTogether(
            name='offer',
            index_together=set([('hotel_id', 'checkin_date'), ('hotel_id', 'checkin_date', 'checkout_date'), ('hotel_id', 'checkout_date')]),
        ),
        migrations.AlterUniqueTogether(
            name='hoteloffer',
            unique_together=set([('hour', 'hotel_id', 'offer_id')]),
        ),
        migrations.AlterIndexTogether(
            name='hoteloffer',
            index_together=set([('hour', 'hotel_id'), ('hour', 'hotel_id', 'days')]),
        ),
    ]
